name: ogjpn-dev
channels:
- conda-forge
dependencies:
- python>=3.10.0
- numpy
- psutil
- scipy>=1.2.3
- pandas>=2.0.0
- matplotlib
- dask>=2023.4.0
- distributed>=2023.4.0
- paramtools>=0.18.1
- taxcalc>=3.3.0
- sphinx>=6.1.3
- sphinx-book-theme>=1.0.1
- pip
- pytest>=7.3.1
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- statsmodels
- linearmodels
- rpy2
- black
- pip:
  - jupyter-book>=0.15.1
  - jupyter-client>=8.2.0
  - sphinxcontrib-bibtex>=2.5.0
  - openpyxl>=3.1.2
  - cs-kit
  - cs2tc
  - pandas-datareader
  - ogcore
