name: Build and test [Python 3.9, 3.10]

on: [push, pull_request]
  # paths:
  #   - '*.py'
  #   - 'environment.yml'
  #   - 'requirements.txt'
  #   - '*.pkl'
  #   - '*.csv'
  #   - '*.json'
  
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Miniconda using Python 3.10
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ogcore-dev
          environment-file: environment.yml
          python-version: "3.10"
          auto-activate-base: false

      - name: Build
        run: |
          pip install -e .
          pip install pytest-cov
          pip install pytest-pycodestyle
      - name: Test
        working-directory: ./
        run: |
          pytest -m 'not local' --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
