name: Build and Deploy Jupyter Book documentation
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.repository == 'Tatsuru-Kikuchi/OG-JPN'
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          activate-environment: ogjpn-dev
          environment-file: environment.yml
          python-version: 3.10
          auto-activate-base: false
          
      - name: Build # Build Jupyter Book
        run: |
          pip install -e .
          pip install jupyter-book>=0.15.1
          pip install sphinxcontrib-bibtex>=2.5.0
          python -m ipykernel install --user --name=ogjpn-dev
          cd docs
          jb build ./book
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/book/_build/html # The folder the action should deploy.
