name: Check that docs build
on: [push, pull_request]

jobs:
  build-and-deploy:
    if: github.repository == 'Tatsuru-Kikuchi/OG-JPN'
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build
          
      - name: Build # Build Jupyter Book
        run: |
          pip install -e .
          pip install jupyter-book>=0.15.1
          pip install sphinxcontrib-bibtex>=2.5.0
          python -m ipykernel install --user --name=ogjpn-dev
          cd docs
          jb build ./book
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/book/_build/html # The folder the action should deploy.
